### ISSUE TITLE
Seems to be broken right now

### ISSUE THREAD

**Issue by adamk33n3r** [TheStonedTurtle/runelite-shields#3]
The api endpoint returns an error with -1 installs. And if you go to https://i.pluginhub.info/generate the plugin select is empty.

**Comment by TheStonedTurtle** [comment]
This has been resolved in commit c59d5dacf0e9172c7106758ac16de40075db489c . This broke due to a change in the RuneLite manifest format.

**Comment by adamk33n3r** [comment]
Made a PR for it #4
